# FashionMNIST Dataset Configuration
dataset:
  name: "fashionmnist"
  batch_size: 64
  num_workers: 2

# Model Architecture
model:
  patch_size: 4
  embed_dim: 128
  num_heads: 8
  num_layers: 6
  latent_dim: 64  # VAE latent space dimension

# Training Parameters
training:
  learning_rate: 0.0003  # Slightly lower LR for FashionMNIST
  weight_decay: 1e-4
  classifier_weight: 0.6  # Higher weight for classification in fashion items
  triplet_margin: 1.2
  
  # Multi-task loss weights - Fashion-MNIST benefits from reconstruction
  use_multitask_loss: true   # Enable multi-task learning for better feature learning
  triplet_weight: 1.0        # Weight for triplet loss in multi-task learning
  classification_weight: 0.6 # Higher classification weight for fashion items
  reconstruction_weight: 1.2 # Higher reconstruction weight for detailed fashion textures
  kl_weight: 0.015           # Slightly higher KL weight for better regularization
  
  # Learning Rate Scheduler
  scheduler:
    type: "CosineAnnealingLR"  # Better for FashionMNIST
    step_size: 7
    gamma: 0.7
    T_max: 15

# Reproducibility
random_seed: 42

# Logging and Saving
logging:
  print_frequency: 100
  save_embeddings_visualization: true
  save_triplet_samples: true
  num_visualization_samples: 5